### ISSUE TITLE
Alpha BUGS

### ISSUE THREAD

**Issue by ivopaunov** [AmbireTech/adex-interface#115]
- [x] add bug here
- [x] https://github.com/orgs/AmbireTech/projects/54/views/1?pane=issue&itemId=60864040

**Comment by Vesi5** [comment]
Onboarding:
- Step 3 is labelled step 2
- Fonts are not the same as the design

Billing details:
- First and Last name should not be mandatory

Top up account with fiat
-  Note that invoices are generated in the currency in which the campaign was initiated - this message should be removed

Dashboard
- if no campaigns have been launched show the onboarding screen
- Placement should be website, not site
- Average CTR and CPM - round to only 2 decimal places, no need to show the whole number 
- CPM - round to 1 decimal place
- Campaign overview window - missing Pause, stop and archive buttons
- Campaign Analytics - graph not working and the impressions are not the same as the ones on the dashboard

Creating campaign
- available banner sizes look clickable as they are right now, we should change that, as it is not intuitive
- Auto utm tracking is not working - not adding utm to the link
- Recommended CPM should be fixed - too low at the moment
- when I click on Select countries only 3 are shown 
- last step with the overview - device type should be changed to Placement and have app or website
- Save as draft is not working
