### ISSUE TITLE
Invoice and Statement design

### ISSUE THREAD

**Issue by Vesi5** [AmbireTech/adex-interface#166]
Here is the design of the invoice and the one for the statement will be provided soon. @MiroslavKr can you upload it here, once it is ready.

![Group 1927](https://github.com/AmbireTech/adex-interface/assets/64790881/377fc86a-ffbc-4042-b1fb-0081ba3b36c0)

**Comment by MiroslavKr** [comment]
https://xd.adobe.com/view/3bfe62ce-6673-44fa-ae98-d12e3aa6f8ff-6ead/screen/2fadbd76-78ff-49be-9b03-25061a51cf32/
