### ISSUE TITLE
Update the robots.txt file

### ISSUE THREAD

**Issue by steboi** [AmbireTech/adex-interface#220]
Update the robots.txt file to allow crawling of the web interface. Change the `disallow` directive to `allow`

More info on the topic can be found here:
https://developers.google.com/search/docs/crawling-indexing/robots/intro
https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt

**Comment by ivopaunov** [comment]
https://github.com/AmbireTech/adex-interface/commit/352d06b020bb37408222ebc613a6f0f748bdd571
