### ISSUE TITLE
Latest UI design changes

### ISSUE THREAD

**Issue by Vesi5** [AmbireTech/adex-interface#39]
Latest design can be found [here](https://xd.adobe.com/view/3bfe62ce-6673-44fa-ae98-d12e3aa6f8ff-6ead/)

The following changes were made to the design that need to be implemented

- [x] Home page: Sub-heading text was changed to Reach Beyond Web3
- [x] "Get started with AdEx": tooltips for onboarding were removed
- [x] Top up account with fiat - The warning message was changed to “Note that invoices are generated in the currency in which the campaign was initiated” 
- [x] Top up account with fiat: An additional warning message was added once you click on an on-ramp regarding the currencies that AdEx operates with
- [x] Dashboard: a “show/hide archive” button was added with which users will be able to see the archived campaigns in the list
- [x] Dashboard, campaign status: 5 additional statuses were added -  active, paused, stopped, archived, rejected
- [x] Campaign overview: stop, cancel, and archive buttons were added
- [x] Analytics, regions: a “show on map” button was added on top, which opens a modal with the map and statistics per country
- [x] Campaign creation, a new first step was added - Selecting Platform - Web or in-app. If Web is selected, second step is to choose device - mobile or desktop; if in-app is selected - second step is to choose banner sizes. 
- [x] Campaign creation, choosing min and max CPM - currency was added to the CPM field, only when using ADX we will show the approx value in $ below the CPM field, a tooltip was added to show the recommended CPM

@IvoPaunov

**Comment by IvoPaunov** [comment]
@Maskln https://github.com/AmbireTech/adex-interface/issues/22#issuecomment-1864173233
