### ISSUE TITLE
Ambire Login SDK integration + Login Screen

### ISSUE THREAD

**Issue by ivopaunov** [AmbireTech/adex-interface#4]
Integrate [Ambire Login SDK](https://github.com/AmbireTech/wallet-login-sdk)

- [x]  SDK integration
- [ ]  Context with hooks for managing account state TODO// multiple tasks here when we know what we will need - balances, pending calls/txns, etc.
- [ ] #5

**Comment by IvoPaunov** [comment]
backend login routes https://github.com/AmbireTech/adex-backend/blob/development/src/routes/dsp.ts

**Comment by ivopaunov** [comment]
There will be no need for sdk balances at the moment as we\ll use backend balances for the alpha
